title: Bodian Ye's Homepage
description: A first year master student in Fudan University
author: Bodian Ye
avatar: /logo.png
email: bdye22@m.fudan.edu.cn
location: Shanghai

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: yizhihenpidehou
  card: summary
logo: logo2.png

social:
  name: Bodian Ye
  links:
    - https://github.com/yizhihenpidehou
lang: en
skin: midnight
plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
subscribe: False
